language: c
compiler:
  - gcc
  - clang

branches:
  only:
    - master

before_install:
  # Update submodules before install
  - git submodule update --init --recursive

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libssl-dev libpcre3 libpcre3-dev

script:
  - make clean all
  - sudo make install

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - jweyrich+travis_pev@gmail.com
  irc:
    on_success: always
    on_failure: always
    channels:
      - "irc.freenode.org#MenteBinaria"
